__author__ = "Jeremy Nelson"

import rdflib

AUTHZ = rdflib.Namespace("http://fedora.info/definitions/v4/authorization#")
BF = rdflib.Namespace("http://bibframe.org/vocab/")
DC = rdflib.Namespace("http://purl.org/dc/elements/1.1/")
FEDORA= rdflib.Namespace("http://fedora.info/definitions/v4/repository#")
FEDORACONFIG = rdflib.Namespace("http://fedora.info/definitions/v4/config#")
FEDORARELSEXT = rdflib.Namespace("http://fedora.info/definitions/v4/rels-ext#")
FOAF = rdflib.Namespace("http://xmlns.com/foaf/0.1/")
IMAGE = rdflib.Namespace("http://www.modeshape.org/images/1.0")
IANA = rdflib.Namespace('http://www.iana.org/assignments/relation/')
INDEXING = rdflib.Namespace("http://fedora.info/definitions/v4/indexing#")
LDP = rdflib.Namespace("http://www.w3.org/ns/ldp#")
MADS = rdflib.Namespace("http://www.loc.gov/mads/rdf/v1#")
MIX = rdflib.Namespace("http://www.jcp.org/jcr/mix/1.0")
MODE = rdflib.Namespace("http://www.modeshape.org/1.0")
NT = rdflib.Namespace("http://www.jcp.org/jcr/nt/1.0")
OB = rdflib.Namespace('http://schema.openbadges.org/')
OWL = rdflib.Namespace("http://www.w3.org/2002/07/owl#")
PTO = rdflib.Namespace("http://www.productontology.org/id/")
PREMIS = rdflib.Namespace("http://www.loc.gov/premis/rdf/v1#")
RDF = rdflib.Namespace("http://www.w3.org/1999/02/22-rdf-syntax-ns#")
RDFS = rdflib.Namespace("http://www.w3.org/2000/01/rdf-schema#")
SCHEMA = rdflib.Namespace("http://schema.org/")
SV = rdflib.Namespace("http://www.jcp.org/jcr/sv/1.0")
TEST = rdflib.Namespace("info:fedora/test/")
XML = rdflib.Namespace("http://www.w3.org/XML/1998/namespace")
XMLNS = rdflib.Namespace("http://www.w3.org/2000/xmlns/")
XSD = rdflib.Namespace("http://www.w3.org/2001/XMLSchema#")
XSI = rdflib.Namespace("http://www.w3.org/2001/XMLSchema-instance")
